### ISSUE TITLE
DeepL Pro Ultimate API key not valid

### ISSUE THREAD

**Issue by jacmaes** [SkyLundy/Fluency#4]
I've installed your wonderful module on a new site a few days ago, with a free DeepL API Key. It worked great. Now today my client tells me they have a DeepL Pro Ultimate account, which they've just let me access to grab the API Key. That new key is not accepted however when I change to account type to Pro: "Translation API authentication failed, check credentials". I'm positive it's the correct key, I've copied and pasted it a few times, even uninstalled and reinstalled the module: 

![api](https://github.com/SkyLundy/Fluency/assets/1206842/5a52bdc0-c7d3-4b7f-9d6c-e25d2d1dba65)

**Comment by jacmaes** [comment]
I think I understand what's going on. Having a Pro Ultimate account doesn't seem to give you access to a paid API plan. That's a separate subscription apparently called DeepL API Pro. Am I correct?

**Comment by SkyLundy** [comment]
@jacmaes I think that may be your issue, there are two "Pro" accounts and only one provides Pro API access. You can tell if the API key you're using is free or Pro because the free key is suffixed with ":fx", a Pro key isn't. A Pro API account will issue you a new key without ":fx".

I'm not directly familiar with how purchasing a Pro account (the non-API Pro account) affects the free API key. My past experience with their API Pro subscription was odd though- I couldn't use the free translator on their website unless I was signed out of my account. It was strange but that experience seems similar to yours, just opposite.

To get a Pro API key you have to purchase the subscription from [this page](https://www.deepl.com/pro-api). The two types of Pro accounts are distinct in that one gets API access and the other does not.

Let me know if that helps.
